import type { ClaimCase } from './models'

export const seedClaims: ClaimCase[] = [
  {
    id: 'CLM-2026-0918',
    policyNo: 'PICC-PROP-882019',
    insured: '上海澄湾食品有限公司',
    lossAddress: '上海市嘉定区兴顺路 88 号 3 号厂房',
    accidentDate: '2026-09-08',
    reportedAt: '2026-09-08 21:32',
    adjuster: '陆嘉 / 华东财产险',
    status: '待复核',
    riskLevel: '高',
    reserve: 1860000,
    paid: 0,
    deductible: 50000,
    lossItems: [
      {
        id: 'LI-01',
        category: '房屋建筑',
        description: '冷库东侧墙体及屋面钢结构',
        damage: '高温烟气熏蚀，屋面檩条局部变形约 18 米。',
        repairQuotes: [
          { version: 1, amount: 680000, reason: '初次现场测量报价', operator: '陈立 / 公估', createdAt: '2026-09-12 10:20' },
          { version: 2, amount: 742000, reason: '补充檩条更换数量和防火涂层恢复费用', operator: '陈立 / 公估', createdAt: '2026-09-18 16:05' },
        ],
        salvage: 18000,
        liability: 0.9,
        disputed: true,
        attachments: [
          { id: 'AT-01', name: '屋面受损全景.jpg', category: '现场照片', version: 2, uploadedBy: '陆嘉', uploadedAt: '09-18 15:20' },
          { id: 'AT-02', name: '结构修复报价_V2.pdf', category: '修复报告', version: 2, uploadedBy: '陈立', uploadedAt: '09-18 16:04' },
          { id: 'AT-03', name: '保单建筑条款摘录.pdf', category: '保单摘录', version: 1, uploadedBy: '陆嘉', uploadedAt: '09-09 09:40' },
        ],
        expertNotes: ['原始测量记录保留为 680,000 元，补充材料不计入原报价版本。', '檩条变形段需由第三方复测确认。'],
      },
      {
        id: 'LI-02',
        category: '机器设备',
        description: '速冻隧道 2 号线',
        damage: '主电机、控制柜和输送带受热损坏。',
        repairQuotes: [
          { version: 1, amount: 520000, reason: '设备厂商初步检修清单', operator: '周岩 / 专家', createdAt: '2026-09-15 14:30' },
        ],
        salvage: 32000,
        liability: 1,
        disputed: false,
        attachments: [{ id: 'AT-04', name: '电机绝缘测试.pdf', category: '专家意见', version: 1, uploadedBy: '周岩', uploadedAt: '09-15 15:10' }],
        expertNotes: ['控制柜以整机更换评估，旧件残值按 6% 计。'],
      },
      {
        id: 'LI-03',
        category: '存货',
        description: '成品冷冻食品',
        damage: '断电导致约 7.2 吨成品解冻变质。',
        repairQuotes: [{ version: 1, amount: 316000, reason: '按库存账面单价和报废数量核算', operator: '陆嘉', createdAt: '2026-09-16 11:08' }],
        salvage: 0,
        liability: 0.85,
        disputed: true,
        attachments: [{ id: 'AT-05', name: '库存盘点表.xlsx', category: '修复报告', version: 3, uploadedBy: '陆嘉', uploadedAt: '09-19 08:35' }],
        expertNotes: ['库龄超过 90 天的部分仍需核减。'],
      },
    ],
    approvals: [
      { role: '查勘员提交', threshold: 0, status: '已通过', operator: '陆嘉', comment: '现场查勘与资料收集完成。', completedAt: '2026-09-19 10:30' },
      { role: '高级核赔员', threshold: 500000, status: '待处理' },
      { role: '理赔经理', threshold: 1000000, status: '待处理' },
      { role: '区域负责人', threshold: 1500000, status: '待处理' },
    ],
    audit: [
      { id: 'A-01', at: '09-08 21:32', operator: '报案中心', action: '案件受理', detail: '完成初步报案信息登记。' },
      { id: 'A-02', at: '09-12 10:20', operator: '陈立', action: '报价录入', detail: '房屋建筑报价 680,000 元。' },
      { id: 'A-03', at: '09-18 16:05', operator: '陈立', action: '报价调整', detail: '由 680,000 调整为 742,000 元；原因：补充檩条更换及防火涂层恢复。' },
      { id: 'A-04', at: '09-19 10:30', operator: '陆嘉', action: '提交审批', detail: '准备金 1,860,000 元进入多级会签。' },
    ],
  },
  {
    id: 'CLM-2026-0927',
    policyNo: 'CPIC-PROP-224108',
    insured: '宁波海岬仓储有限公司',
    lossAddress: '宁波北仑区海盛路 14 号',
    accidentDate: '2026-09-21',
    reportedAt: '2026-09-21 06:18',
    adjuster: '林澈 / 浙江财产险',
    status: '查勘中',
    riskLevel: '中',
    reserve: 860000,
    paid: 0,
    deductible: 20000,
    lossItems: [
      {
        id: 'LI-11',
        category: '房屋建筑',
        description: '仓储库房屋面和排水天沟',
        damage: '台风造成局部彩钢瓦掀起，雨水进入库区。',
        repairQuotes: [{ version: 1, amount: 420000, reason: '维修单位预算', operator: '林澈', createdAt: '2026-09-23 13:50' }],
        salvage: 8000,
        liability: 1,
        disputed: false,
        attachments: [{ id: 'AT-11', name: '屋面无损段对照.jpg', category: '现场照片', version: 1, uploadedBy: '林澈', uploadedAt: '09-22 09:15' }],
        expertNotes: [],
      },
      {
        id: 'LI-12',
        category: '存货',
        description: '进口纸浆',
        damage: '约 38 托受潮，需分拣降级处理。',
        repairQuotes: [{ version: 1, amount: 440000, reason: '按采购发票与可回收比例计算', operator: '林澈', createdAt: '2026-09-24 16:20' }],
        salvage: 96000,
        liability: 0.8,
        disputed: false,
        attachments: [],
        expertNotes: ['待第三方测水报告确认降级率。'],
      },
    ],
    approvals: [
      { role: '查勘员提交', threshold: 0, status: '已通过', operator: '林澈', completedAt: '2026-09-24 17:00' },
      { role: '高级核赔员', threshold: 500000, status: '待处理' },
      { role: '理赔经理', threshold: 1000000, status: '待处理' },
    ],
    audit: [
      { id: 'A-11', at: '09-21 06:18', operator: '报案中心', action: '案件受理', detail: '台风损失报案。' },
      { id: 'A-12', at: '09-22 09:15', operator: '林澈', action: '现场查勘', detail: '上传屋顶和库区照片。' },
    ],
  },
]
